
MYSQL_HOST = 'localhost'
MYSQL_USER = 'root'
MYSQL_PASSWD = ''
MYSQL_DB = 'wangcai_task'

TASK_MQ_HOST = 'localhost'
TASK_MQ_PORT = 6379
TASK_MQ_CHANNEL = 'wangcai:task'

BILLING_MQ_HOST = 'localhost'
BILLING_MQ_PORT = 6379
BILLING_MQ_CHANNEL = 'wangcai:billing'

ACCOUNT_BACKEND = '127.0.0.1:15281'
BILLING_BACKEND = '127.0.0.1:15283'

TASK_INVITE_NUM_MAX = 20

TASK_REWARD_NEWBIE = 100
TASK_REWARD_INFO = 100
TASK_REWARD_INVITEE = 200
TASK_REWARD_COMMENT = 10



